<a href="https://colab.research.google.com/github/manikantan259/tusk/blob/master/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
type(100)

int

In [ ]:
type(1)

int

In [ ]:
a = " Mani"

In [ ]:
a


' Mani'

In [ ]:
type([])

list

In [ ]:
example =["Math",1,1.3,'a']

In [ ]:
type(example)

list

In [ ]:
example

['Math', 1, 1.3, 'a']

In [ ]:
example[1]

1

In [ ]:
example.append("Mani1")

In [ ]:
example.append(["Mani2","Mani3"])

In [ ]:
example

['Math', 1, 1.3, 'a', 'Mani1', ['Mani2', 'Mani3']]

In [ ]:
example.insert(1,"Insert")

In [ ]:
example

['Math', 'Insert', 1, 1.3, 'a', 'Mani1', ['Mani2', 'Mani3']]

In [ ]:
example.extend([8,9])

In [ ]:
example

['Math', 'Insert', 1, 1.3, 'a', 'Mani1', ['Mani2', 'Mani3'], 8, 9]

In [ ]:
lst=[1,2,3,4,5]
sum(lst)

15

In [ ]:
lst*5

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
lst.pop()

5

In [ ]:
lst.pop(0)

1

In [ ]:
pract = [1,2,3]
pract.append(4)
pract.append(["5",6])
pract.extend([7,8])
pract.insert(9,9)


In [ ]:
pract

[1, 2, 3, 4, ['5', 6], 7, 8, 9]

In [ ]:
pract.pop()

9

In [ ]:
pract.pop(1)

2

In [ ]:
len(pract)

6

In [ ]:
for i in example:
  print (i)

Math
Insert
1
1.3
a
Mani1
['Mani2', 'Mani3']
8
9


In [ ]:
example[::-1]

[9, 8, ['Mani2', 'Mani3'], 'Mani1', 'a', 1.3, 1, 'Insert', 'Math']

In [ ]:
set={1,2,3,4,5}

In [ ]:
set

{1, 2, 3, 4, 5}

In [ ]:
set.add(6)

In [ ]:
set1={"Avengers","IronMan",'Hitman'}
set2={"Avengers","IronMan",'Hitman','Hulk2'}

In [ ]:
set2.intersection_update(set1)

In [ ]:
set2

{'Avengers', 'Hitman', 'IronMan'}

In [ ]:
set1.intersection_update(set2)

In [ ]:
set1

{'Avengers', 'Hitman', 'IronMan'}

In [ ]:
set2.difference(set1)

{'Hulk2'}

In [ ]:
set2.difference_update(set1)

In [ ]:
set2

{'Hulk2'}

In [ ]:
dic={1:"one",2:"two",3:"three"}

In [ ]:
dic

{1: 'one', 2: 'two', 3: 'three'}

In [ ]:
for i in dic.values():
  print(i)

one
two
three


In [ ]:
for i in dic:
  print (i)

1
2
3


In [ ]:
for i in dic.items():
  print(i)

(1, 'one')
(2, 'two')
(3, 'three')


In [ ]:
dic[1]

'one'

In [ ]:
dic[4]="four"

In [ ]:
dic

{1: 'one', 2: 'two', 3: 'three', 4: 'four'}

In [ ]:
car1_model={'Mercedes':1960}
car2_model={'Audi':1970}
car3_model={'Ambassador':1980}

In [ ]:
car = {'1':car1_model,'2':car2_model,'3':car3_model}

In [ ]:
car

{'1': {'Mercedes': 1960}, '2': {'Audi': 1970}, '3': {'Ambassador': 1980}}

In [ ]:
car['1']

{'Mercedes': 1960}

In [ ]:
car['1']["Mercedes"]

1960

In [ ]:
my_tuple=("Krish","Ankur","John")

In [ ]:
import numpy as np


In [ ]:
my_list= [1,2,3,4,5]

arr = np.array(my_list)

In [ ]:
print(arr)

[1 2 3 4 5]


In [ ]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr2 = np.array([my_lst1,my_lst2,my_lst3])

In [ ]:
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
print(arr2)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [ ]:
arr.shape

(5,)

In [ ]:
arr2.shape

(3, 5)

In [ ]:
arr2.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

In [ ]:
arr2.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [ ]:
arr[3]

4

In [ ]:
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
arr2[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [ ]:
a =arr2[:2]
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [ ]:
a[:2,0:2]

array([[1, 2],
       [2, 3]])

In [ ]:
arr2[1:,3:]

array([[5, 6],
       [8, 9]])

In [ ]:
arr2[1: ,2:4]

array([[4, 5],
       [6, 8]])

In [ ]:
b = np.arange(0,10)

In [ ]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
np.linspace (1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
b[3:] =100

In [ ]:
b

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
b<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [ ]:
b*2

array([  0,   2,   4, 200, 200, 200, 200, 200, 200, 200])

In [ ]:
val = 2
b[b < val]

array([0, 1])

In [ ]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.random.rand(3,3)

array([[0.07004868, 0.58462753, 0.20058941],
       [0.21453935, 0.35541838, 0.15380604],
       [0.05247672, 0.47874323, 0.60757043]])

In [ ]:
np.random.randint(0,100,8).reshape(2,4)

array([[18, 31, 12, 40],
       [91, 73, 64, 98]])

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('services.csv')

In [ ]:
df.head()

id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN   
1   2            2         NaN               NaN            NaN   
2   3            3         NaN               NaN            NaN   
3   4            4         NaN               NaN            NaN   
4   5            5         NaN               NaN            NaN   

                           application_process  \
0                   Walk in or apply by phone.   
1           Apply by phone for an appointment.   
2  Phone for information (403-4300 Ext. 4322).   
3                              Apply by phone.   
4                       Phone for information.   

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...   
1       Residents of San Mateo County age 55 or over   
2  Older adults age 55 or over who can benefit fr...   
3  Parents, children, families with problems of c...   
4  Low-income working families with children tran...   

                                         description  \
0  A walk-in center for older adults that provide...   
1  Provides training and job placement to eligibl...   
2  Offers supportive counseling services to San M...   
3  Provides supervised visitation services and a ...   
4  Provides fixed 8% short term loans to eligible...   

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...   
1  Age 55 or over, county resident and willing an...   NaN  ...   
2        Resident of San Mateo County age 55 or over   NaN  ...   
3                                               None   NaN  ...   
4  Eligibility: Low-income family with legal cust...   NaN  ...   

  interpretation_services                                           keywords  \
0                     NaN  ADULT PROTECTION AND CARE SERVICES, Meal Sites...   
1                     NaN  EMPLOYMENT/TRAINING SERVICES, Job Development,...   
2                     NaN  Geriatric Counseling, Older Adults, Gay, Lesbi...   
3                     NaN  INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...   
4                     NaN     COMMUNITY SERVICES, Speakers, Automobile Loans   

  languages                               name required_documents  \
0       NaN    Fair Oaks Adult Activity Center                NaN   
1       NaN   Second Career Employment Program                NaN   
2       NaN             Senior Peer Counseling                NaN   
3       NaN           Family Visitation Center                NaN   
4       NaN  Economic Self-Sufficiency Program                NaN   

      service_areas  status wait_time website taxonomy_ids  
0             Colma  active  No wait.     NaN          NaN  
1  San Mateo County  active   Varies.     NaN          NaN  
2  San Mateo County  active   Varies.     NaN          NaN  
3  San Mateo County  active  No wait.     NaN          NaN  
4  San Mateo County  active       NaN     NaN          NaN  

[5 rows x 22 columns]

In [ ]:
df.columns

Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='object')

In [ ]:
list(df.columns)

['id',
 'location_id',
 'program_id',
 'accepted_payments',
 'alternate_name',
 'application_process',
 'audience',
 'description',
 'eligibility',
 'email',
 'fees',
 'funding_sources',
 'interpretation_services',
 'keywords',
 'languages',
 'name',
 'required_documents',
 'service_areas',
 'status',
 'wait_time',
 'website',
 'taxonomy_ids']

In [ ]:
df.tail()

id  location_id  program_id         accepted_payments  \
18  19           19         NaN                       NaN   
19  20           20         NaN                       NaN   
20  21           21         NaN                       NaN   
21  22           22         NaN  Cash, Check, Credit Card   
22  23           22         NaN                       NaN   

           alternate_name                             application_process  \
18                    NaN  Call for screening appointment (650-347-3648).   
19                    NaN                                        Walk in.   
20                    NaN                 By phone during business hours.   
21  Fotos para pasaportes               Walk in or apply by phone or mail   
22                    NaN               Walk in or apply by phone or mail   

                                             audience  \
18                                                NaN   
19                                                NaN   
20                                                NaN   
21  Profit and nonprofit businesses, the public, m...   
22  Second service and nonprofit businesses, the p...   

                                          description  \
18  Provides free medical and dental care to those...   
19              no unrequired fields for this service   
20                                just a test service   
21  [NOTE THIS IS NOT A REAL SERVICE--THIS IS FOR ...   
22  [NOTE THIS IS NOT A REAL ORGANIZATION--THIS IS...   

                                        eligibility                  email  \
18  Low-income person without access to health care                    NaN   
19                                              NaN                    NaN   
20                                              NaN                    NaN   
21                                             None  passports@example.org   
22                                             None                    NaN   

    ...                            interpretation_services  \
18  ...                                                NaN   
19  ...                                                NaN   
20  ...                                                NaN   
21  ...  We offer 3-way interpretation services over th...   
22  ...                                                NaN   

                                             keywords languages  \
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN   
19                                                NaN       NaN   
20                                                NaN       NaN   
21                                    Salud, Medicina   Spanish   
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN   

                               name                        required_documents  \
18    San Mateo Free Medical Clinic                                       NaN   
19        Service with blank fields                                       NaN   
20  Service for Admin Test Location                                       NaN   
21                  Passport Photos  Government-issued picture identification   
22             Example Service Name                                       NaN   

                       service_areas    status            wait_time  \
18               Belmont, Burlingame    active              Varies.   
19                               NaN   defunct                  NaN   
20                  San Mateo County  inactive                  NaN   
21  Alameda County, San Mateo County    active  No wait to 2 weeks.   
22  San Mateo County, Alameda County    active   No wait to 2 weeks   

                   website                              taxonomy_ids  
18                     NaN                                       NaN  
19                     NaN                                       NaN  
20                     NaN                                       NaN  
21  http://www.example.com  105, 108, 108-05,

In [ ]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [ ]:
df['application_process']

0                            Walk in or apply by phone.
1                    Apply by phone for an appointment.
2           Phone for information (403-4300 Ext. 4322).
3                                       Apply by phone.
4                                Phone for information.
5     Walk in or apply by phone for membership appli...
6     Apply by phone or be referred by a doctor, soc...
7                                       Apply by phone.
8     Walk in. Proof of residency in California requ...
9     Walk in. Proof of California residency to rece...
10    Walk in. Proof of California residency require...
11    Walk in or apply by phone, email or webpage re...
12    Walk in. Proof of California residency require...
13    Call for appointment. Referral from human serv...
14            Walk in or through other agency referral.
15    Walk in. Written application, identification r...
16                                Call for information.
17    Call for screening appointment. Medical vi

In [ ]:
type(df['application_process'])

pandas.core.series.Series

In [ ]:
list(df['application_process'])

['Walk in or apply by phone.',
 'Apply by phone for an appointment.',
 'Phone for information (403-4300 Ext. 4322).',
 'Apply by phone.',
 'Phone for information.',
 'Walk in or apply by phone for membership application.',
 'Apply by phone or be referred by a doctor, social worker or other professional. All prospective participants are interviewed individually before starting the program. A recent physical examination is required, including a TB test.',
 'Apply by phone.',
 'Walk in. Proof of residency in California required to receive a library card.',
 'Walk in. Proof of California residency to receive a library card.',
 'Walk in. Proof of California residency required to receive a library card.',
 'Walk in or apply by phone, email or webpage registration.',
 'Walk in. Proof of California residency required to receive a library card.',
 'Call for appointment. Referral from human service professional preferred for emergency assistance.',
 'Walk in or through other agency referral.',
 

In [ ]:
df[['name','keywords']]

name  \
0        Fair Oaks Adult Activity Center   
1       Second Career Employment Program   
2                 Senior Peer Counseling   
3               Family Visitation Center   
4      Economic Self-Sufficiency Program   
5   Little House Recreational Activities   
6       Rosener House Adult Day Services   
7         Meals on Wheels - South County   
8                       Fair Oaks Branch   
9                           Main Library   
10                       Schaberg Branch   
11                          Project Read   
12                 Redwood Shores Branch   
13                    Redwood City Corps   
14           Adult Rehabilitation Center   
15                       Sunnyvale Corps   
16     South San Francisco Citadel Corps   
17                         Project Smile   
18         San Mateo Free Medical Clinic   
19             Service with blank fields   
20       Service for Admin Test Location   
21                       Passport Photos   
22                  Example Service Name   

                                             keywords  
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...  
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...  
2   Geriatric Counseling, Older Adults, Gay, Lesbi...  
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...  
4      COMMUNITY SERVICES, Speakers, Automobile Loans  
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...  
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...  
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...  
8   EDUCATION SERVICES, Library, Libraries, Public...  
9   EDUCATION SERVICES, Library, Libraries, Public...  
10  EDUCATION SERVICES, Library, Libraries, Public...  
11  EDUCATION SERVICES, Adult, Alternative, Litera...  
12  EDUCATION SERVICES, Library, Libraries, Public...  
13  COMMUNITY SERVICES, Interpretation/Translation...  
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...  
15  COMMODITY SERVICES, Clothing/Personal Items, C...  
16  COMMODITY SERVICES, Clothing/Personal Items, C...  
17  HEALTH SERVICES, Outpatient Care, Community Cl...  
18  HEALTH SERVICES, Outpatient Care, Community Cl...  
19                                                NaN  
20                                                NaN  
21                                    Salud, Medicina  
22         Ruby on Rails/Postgres/Redis, testing, wic

In [ ]:
df[[  'interpretation_services', 'keywords', 'languages', 'name']]

interpretation_services  \
0                                                 NaN   
1                                                 NaN   
2                                                 NaN   
3                                                 NaN   
4                                                 NaN   
5                                                 NaN   
6                                                 NaN   
7                                                 NaN   
8                                                 NaN   
9                                                 NaN   
10                                                NaN   
11                                                NaN   
12                                                NaN   
13                                                NaN   
14                                                NaN   
15                                                NaN   
16                                                NaN   
17                                                NaN   
18                                                NaN   
19                                                NaN   
20                                                NaN   
21  We offer 3-way interpretation services over th...   
22                                                NaN   

                                             keywords languages  \
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN   
2   Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN   
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN   
4      COMMUNITY SERVICES, Speakers, Automobile Loans       NaN   
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN   
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...       NaN   
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
8   EDUCATION SERVICES, Library, Libraries, Public...       NaN   
9   EDUCATION SERVICES, Library, Libraries, Public...       NaN   
10  EDUCATION SERVICES, Library, Libraries, Public...       NaN   
11  EDUCATION SERVICES, Adult, Alternative, Litera...       NaN   
12  EDUCATION SERVICES, Library, Libraries, Public...       NaN   
13  COMMUNITY SERVICES, Interpretation/Translation...       NaN   
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...       NaN   
15  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN   
16  COMMODITY SERVICES, Clothing/Personal Items, C...       NaN   
17  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN   
18  HEALTH SERVICES, Outpatient Care, Community Cl...       NaN   
19                                                NaN       NaN   
20                                                NaN       NaN   
21                                    Salud, Medicina   Spanish   
22         Ruby on Rails/Postgres/Redis, testing, wic       NaN   

                                    name  
0        Fair Oaks Adult Activity Center  
1       Second Career Employment Program  
2                 Senior Peer Counseling  
3               Family Visitation Center  
4      Economic Self-Sufficiency Program  
5   Little House Recreational Activities  
6       Rosener House Adult Day Services  
7         Meals on Wheels - South County  
8                       Fair Oaks Branch  
9                           Main Library  
10                       Schaberg Branch  
11                          Project Read  
12                 Redwood Shores Branch  
13                    Redwood City Corps  
14           Adult Rehabilitation Center  
15                       Sunnyvale Corps  
16     South San Francisco Citadel Corps  
17                         Project Smile  
18         San Mateo Free Medical Clinic  
19             Service with blank fields  
20       Service for Admin Test Location  
21                       Passport Photos  
22                  Example Service Name

In [ ]:
df[['name','keywords']]

name  \
0        Fair Oaks Adult Activity Center   
1       Second Career Employment Program   
2                 Senior Peer Counseling   
3               Family Visitation Center   
4      Economic Self-Sufficiency Program   
5   Little House Recreational Activities   
6       Rosener House Adult Day Services   
7         Meals on Wheels - South County   
8                       Fair Oaks Branch   
9                           Main Library   
10                       Schaberg Branch   
11                          Project Read   
12                 Redwood Shores Branch   
13                    Redwood City Corps   
14           Adult Rehabilitation Center   
15                       Sunnyvale Corps   
16     South San Francisco Citadel Corps   
17                         Project Smile   
18         San Mateo Free Medical Clinic   
19             Service with blank fields   
20       Service for Admin Test Location   
21                       Passport Photos   
22                  Example Service Name   

                                             keywords  
0   ADULT PROTECTION AND CARE SERVICES, Meal Sites...  
1   EMPLOYMENT/TRAINING SERVICES, Job Development,...  
2   Geriatric Counseling, Older Adults, Gay, Lesbi...  
3   INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...  
4      COMMUNITY SERVICES, Speakers, Automobile Loans  
5   ADULT PROTECTION AND CARE SERVICES, In-Home Su...  
6   ADULT PROTECTION AND CARE SERVICES, Adult Day ...  
7   ADULT PROTECTION AND CARE SERVICES, Meal Sites...  
8   EDUCATION SERVICES, Library, Libraries, Public...  
9   EDUCATION SERVICES, Library, Libraries, Public...  
10  EDUCATION SERVICES, Library, Libraries, Public...  
11  EDUCATION SERVICES, Adult, Alternative, Litera...  
12  EDUCATION SERVICES, Library, Libraries, Public...  
13  COMMUNITY SERVICES, Interpretation/Translation...  
14  ALCOHOLISM SERVICES, Residential Care, DRUG AB...  
15  COMMODITY SERVICES, Clothing/Personal Items, C...  
16  COMMODITY SERVICES, Clothing/Personal Items, C...  
17  HEALTH SERVICES, Outpatient Care, Community Cl...  
18  HEALTH SERVICES, Outpatient Care, Community Cl...  
19                                                NaN  
20                                                NaN  
21                                    Salud, Medicina  
22         Ruby on Rails/Postgres/Redis, testing, wic

In [ ]:
df.describe()

id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
25%     6.50000     6.500000         NaN
50%    12.00000    12.000000         NaN
75%    17.50000    17.500000         NaN
max    23.00000    22.000000         NaN

In [ ]:
df.dtypes

id                           int64
location_id                  int64
program_id                 float64
accepted_payments           object
alternate_name              object
application_process         object
audience                    object
description                 object
eligibility                 object
email                       object
fees                        object
funding_sources             object
interpretation_services     object
keywords                    object
languages                   object
name                        object
required_documents          object
service_areas               object
status                      object
wait_time                   object
website                     object
taxonomy_ids                object
dtype: object

In [ ]:
df.dtypes[df.dtypes=="object"].index

Index(['accepted_payments', 'alternate_name', 'application_process',
       'audience', 'description', 'eligibility', 'email', 'fees',
       'funding_sources', 'interpretation_services', 'keywords', 'languages',
       'name', 'required_documents', 'service_areas', 'status', 'wait_time',
       'website', 'taxonomy_ids'],
      dtype='object')

In [ ]:
df.dtypes=="object"

id                         False
location_id                False
program_id                 False
accepted_payments           True
alternate_name              True
application_process         True
audience                    True
description                 True
eligibility                 True
email                       True
fees                        True
funding_sources             True
interpretation_services     True
keywords                    True
languages                   True
name                        True
required_documents          True
service_areas               True
status                      True
wait_time                   True
website                     True
taxonomy_ids                True
dtype: bool

In [ ]:
df.dtypes[df.dtypes=="object"]

accepted_payments          object
alternate_name             object
application_process        object
audience                   object
description                object
eligibility                object
email                      object
fees                       object
funding_sources            object
interpretation_services    object
keywords                   object
languages                  object
name                       object
required_documents         object
service_areas              object
status                     object
wait_time                  object
website                    object
taxonomy_ids               object
dtype: object

In [ ]:
df[df.dtypes[df.dtypes=="object"].index]

accepted_payments         alternate_name  \
0                        NaN                    NaN   
1                        NaN                    NaN   
2                        NaN                    NaN   
3                        NaN                    NaN   
4                        NaN                    NaN   
5                        NaN                    NaN   
6                        NaN                    NaN   
7                        NaN                    NaN   
8                        NaN                    NaN   
9                        NaN                    NaN   
10                       NaN                    NaN   
11                       NaN                    NaN   
12                       NaN                    NaN   
13                       NaN                    NaN   
14                       NaN                    NaN   
15                       NaN                    NaN   
16                       NaN                    NaN   
17                       NaN                    NaN   
18                       NaN                    NaN   
19                       NaN                    NaN   
20                       NaN                    NaN   
21  Cash, Check, Credit Card  Fotos para pasaportes   
22                       NaN                    NaN   

                                  application_process  \
0                          Walk in or apply by phone.   
1                  Apply by phone for an appointment.   
2         Phone for information (403-4300 Ext. 4322).   
3                                     Apply by phone.   
4                              Phone for information.   
5   Walk in or apply by phone for membership appli...   
6   Apply by phone or be referred by a doctor, soc...   
7                                     Apply by phone.   
8   Walk in. Proof of residency in California requ...   
9   Walk in. Proof of California residency to rece...   
10  Walk in. Proof of California residency require...   
11  Walk in or apply by phone, email or webpage re...   
12  Walk in. Proof of California residency require...   
13  Call for appointment. Referral from human serv...   
14          Walk in or through other agency referral.   
15  Walk in. Written application, identification r...   
16                              Call for information.   
17  Call for screening appointment. Medical visits...   
18     Call for screening appointment (650-347-3648).   
19                                           Walk in.   
20                    By phone during business hours.   
21                  Walk in or apply by phone or mail   
22                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
3   Parents, children, families with problems of c...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, ...   
7   Senior citizens age 60 or over, disabled indiv...   
8      Ethnic minorities, especially Spanish speaking   
9                                                 NaN   
10                                                NaN   
11  Adults, parents, children in 1st-12th grades i...   
12                                                NaN   
13  Individuals or families with low or no income ...   
14  Adult alcoholic/drug addictive men and women w...   
15                                                NaN   
16                                                NaN   
17                                                NaN   
18                                                NaN   
19                                                NaN   
20                                                NaN   
21  Profit and nonprofit businesses, the public, m...   
22  Second

In [ ]:
df[df.dtypes[df.dtypes=="object"].index].describe()

accepted_payments         alternate_name  \
count                          1                      1   
unique                         1                      1   
top     Cash, Check, Credit Card  Fotos para pasaportes   
freq                           1                      1   

                      application_process  \
count                                  23   
unique                                 20   
top     Walk in or apply by phone or mail   
freq                                    2   

                                                 audience  \
count                                                  14   
unique                                                 14   
top     Older adults age 55 or over, ethnic minorities...   
freq                                                    1   

                                              description eligibility  \
count                                                  23          21   
unique                                                 23          16   
top     A walk-in center for older adults that provide...        None   
freq                                                    1           4   

                        email   fees funding_sources  \
count                       1     21              21   
unique                      1     10              14   
top     passports@example.org  None.            City   
freq                        1     11               3   

                                  interpretation_services  \
count                                                   1   
unique                                                  1   
top     We offer 3-way interpretation services over th...   
freq                                                    1   

                                                 keywords languages  \
count                                                  21         1   
unique                                                 18         1   
top     EDUCATION SERVICES, Library, Libraries, Public...   Spanish   
freq                                                    4         1   

                                   name  \
count                                23   
unique                               23   
top     Fair Oaks Adult Activity Center   
freq                                  1   

                              required_documents     service_areas  status  \
count                                          1                21      23   
unique                                         1                10       3   
top     Government-issued picture identification  San Mateo County  active   
freq                                           1                10      21   

       wait_time                 website  \
count         19                       2   
unique         7                       1   
top     No wait.  http://www.example.com   
freq          10                       2   

                                    taxonomy_ids  
count                                          1  
unique                                         1  
top     105, 108, 108-05, 108-05-01, 111, 111-05  
freq                                           1

In [ ]:
df["eligibility"][2:10]

2          Resident of San Mateo County age 55 or over
3                                                 None
4    Eligibility: Low-income family with legal cust...
5                                                 None
6                                       Age 18 or over
7              Homebound person unable to cook or shop
8      Resident of California to obtain a library card
9              Resident of California to obtain a card
Name: eligibility, dtype: object

In [ ]:
df["eligibility"][2:10:2]

2          Resident of San Mateo County age 55 or over
4    Eligibility: Low-income family with legal cust...
6                                       Age 18 or over
8      Resident of California to obtain a library card
Name: eligibility, dtype: object

In [ ]:
df["new"] =df['accepted_payments']+df["application_process"]

In [ ]:
df.head()

id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN   
1   2            2         NaN               NaN            NaN   
2   3            3         NaN               NaN            NaN   
3   4            4         NaN               NaN            NaN   
4   5            5         NaN               NaN            NaN   

                           application_process  \
0                   Walk in or apply by phone.   
1           Apply by phone for an appointment.   
2  Phone for information (403-4300 Ext. 4322).   
3                              Apply by phone.   
4                       Phone for information.   

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...   
1       Residents of San Mateo County age 55 or over   
2  Older adults age 55 or over who can benefit fr...   
3  Parents, children, families with problems of c...   
4  Low-income working families with children tran...   

                                         description  \
0  A walk-in center for older adults that provide...   
1  Provides training and job placement to eligibl...   
2  Offers supportive counseling services to San M...   
3  Provides supervised visitation services and a ...   
4  Provides fixed 8% short term loans to eligible...   

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...   
1  Age 55 or over, county resident and willing an...   NaN  ...   
2        Resident of San Mateo County age 55 or over   NaN  ...   
3                                               None   NaN  ...   
4  Eligibility: Low-income family with legal cust...   NaN  ...   

                                            keywords languages  \
0  ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
1  EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN   
2  Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN   
3  INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN   
4     COMMUNITY SERVICES, Speakers, Automobile Loans       NaN   

                                name required_documents     service_areas  \
0    Fair Oaks Adult Activity Center                NaN             Colma   
1   Second Career Employment Program                NaN  San Mateo County   
2             Senior Peer Counseling                NaN  San Mateo County   
3           Family Visitation Center                NaN  San Mateo County   
4  Economic Self-Sufficiency Program                NaN  San Mateo County   

   status wait_time website taxonomy_ids  new  
0  active  No wait.     NaN          NaN  NaN  
1  active   Varies.     NaN          NaN  NaN  
2  active   Varies.     NaN          NaN  NaN  
3  active  No wait.     NaN          NaN  NaN  
4  active       NaN     NaN          NaN  NaN  

[5 rows x 23 columns]

In [ ]:
df.describe()

id  location_id  program_id
count  23.00000    23.000000         0.0
mean   12.00000    11.956522         NaN
std     6.78233     6.711444         NaN
min     1.00000     1.000000         NaN
25%     6.50000     6.500000         NaN
50%    12.00000    12.000000         NaN
75%    17.50000    17.500000         NaN
max    23.00000    22.000000         NaN

In [ ]:
df["wait_time"].unique()

array(['No wait.', 'Varies.', nan,
       'Depends on availability of tutors for small groups and one-on-one.',
       'Up to 20 minutes.',
       'Varies according to available beds for men and women. Women have a longer wait due to small number of beds statewide.',
       'No wait to 2 weeks.', 'No wait to 2 weeks'], dtype=object)

In [ ]:
df[df["location_id"]<10]

id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN   
1   2            2         NaN               NaN            NaN   
2   3            3         NaN               NaN            NaN   
3   4            4         NaN               NaN            NaN   
4   5            5         NaN               NaN            NaN   
5   6            6         NaN               NaN            NaN   
6   7            7         NaN               NaN            NaN   
7   8            8         NaN               NaN            NaN   
8   9            9         NaN               NaN            NaN   

                                 application_process  \
0                         Walk in or apply by phone.   
1                 Apply by phone for an appointment.   
2        Phone for information (403-4300 Ext. 4322).   
3                                    Apply by phone.   
4                             Phone for information.   
5  Walk in or apply by phone for membership appli...   
6  Apply by phone or be referred by a doctor, soc...   
7                                    Apply by phone.   
8  Walk in. Proof of residency in California requ...   

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...   
1       Residents of San Mateo County age 55 or over   
2  Older adults age 55 or over who can benefit fr...   
3  Parents, children, families with problems of c...   
4  Low-income working families with children tran...   
5                                            Any age   
6  Older adults who have memory or sensory loss, ...   
7  Senior citizens age 60 or over, disabled indiv...   
8     Ethnic minorities, especially Spanish speaking   

                                         description  \
0  A walk-in center for older adults that provide...   
1  Provides training and job placement to eligibl...   
2  Offers supportive counseling services to San M...   
3  Provides supervised visitation services and a ...   
4  Provides fixed 8% short term loans to eligible...   
5  A multipurpose center offering a wide variety ...   
6  Rosener House is a day center for older adults...   
7  Delivers a hot meal to the home of persons age...   
8  Provides general reading material, including b...   

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...   
1  Age 55 or over, county resident and willing an...   NaN  ...   
2        Resident of San Mateo County age 55 or over   NaN  ...   
3                                               None   NaN  ...   
4  Eligibility: Low-income family with legal cust...   NaN  ...   
5                                               None   NaN  ...   
6                                     Age 18 or over   NaN  ...   
7            Homebound person unable to cook or shop   NaN  ...   
8    Resident of California to obtain a library card   NaN  ...   

                                            keywords languages  \
0  ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
1  EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN   
2  Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN   
3  INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN   
4     COMMUNITY SERVICES, Speakers, Automobile Loans       NaN   
5  ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN   
6  ADULT PROTECTION AND CARE SERVICES, Adult Day ...       NaN   
7  ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
8  EDUCATION SERVICES, Library, Libraries, Public...       NaN   

                                   name required_documents  \
0       Fair Oaks Adult Activity Center                NaN   
1      Second Career Employment Program                NaN   
2                Senior Peer Counseling                NaN   
3              Family Visitation Center                NaN   
4     E

In [ ]:
len(df)

23

In [ ]:
df[df["location_id"]<10]["audience"]

0    Older adults age 55 or over, ethnic minorities...
1         Residents of San Mateo County age 55 or over
2    Older adults age 55 or over who can benefit fr...
3    Parents, children, families with problems of c...
4    Low-income working families with children tran...
5                                              Any age
6    Older adults who have memory or sensory loss, ...
7    Senior citizens age 60 or over, disabled indiv...
8       Ethnic minorities, especially Spanish speaking
Name: audience, dtype: object

In [ ]:
df[df["status"]=="active"]

id  location_id  program_id         accepted_payments  \
0    1            1         NaN                       NaN   
1    2            2         NaN                       NaN   
2    3            3         NaN                       NaN   
3    4            4         NaN                       NaN   
4    5            5         NaN                       NaN   
5    6            6         NaN                       NaN   
6    7            7         NaN                       NaN   
7    8            8         NaN                       NaN   
8    9            9         NaN                       NaN   
9   10           10         NaN                       NaN   
10  11           11         NaN                       NaN   
11  12           12         NaN                       NaN   
12  13           13         NaN                       NaN   
13  14           14         NaN                       NaN   
14  15           15         NaN                       NaN   
15  16           16         NaN                       NaN   
16  17           17         NaN                       NaN   
17  18           18         NaN                       NaN   
18  19           19         NaN                       NaN   
21  22           22         NaN  Cash, Check, Credit Card   
22  23           22         NaN                       NaN   

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.   
1                     NaN                 Apply by phone for an appointment.   
2                     NaN        Phone for information (403-4300 Ext. 4322).   
3                     NaN                                    Apply by phone.   
4                     NaN                             Phone for information.   
5                     NaN  Walk in or apply by phone for membership appli...   
6                     NaN  Apply by phone or be referred by a doctor, soc...   
7                     NaN                                    Apply by phone.   
8                     NaN  Walk in. Proof of residency in California requ...   
9                     NaN  Walk in. Proof of California residency to rece...   
10                    NaN  Walk in. Proof of California residency require...   
11                    NaN  Walk in or apply by phone, email or webpage re...   
12                    NaN  Walk in. Proof of California residency require...   
13                    NaN  Call for appointment. Referral from human serv...   
14                    NaN          Walk in or through other agency referral.   
15                    NaN  Walk in. Written application, identification r...   
16                    NaN                              Call for information.   
17                    NaN  Call for screening appointment. Medical visits...   
18                    NaN     Call for screening appointment (650-347-3648).   
21  Fotos para pasaportes                  Walk in or apply by phone or mail   
22                    NaN                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
3   Parents, children, families with problems of c...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, ...   
7   Senior citizens age 60 or over, disabled indiv...   
8      Ethnic minorities, especially Spanish speaking   
9                                                 NaN   
10                                                NaN   
11  Adults, parents, children in 1st-12th grades i...   
12                                                NaN   
13  Individuals or families with low or no income ...   
14  Adult alcoholic/drug addictive men and wo

In [ ]:


df[(df["location_id"]<10 )&(df["status"]=="active")]

id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN   
1   2            2         NaN               NaN            NaN   
2   3            3         NaN               NaN            NaN   
3   4            4         NaN               NaN            NaN   
4   5            5         NaN               NaN            NaN   
5   6            6         NaN               NaN            NaN   
6   7            7         NaN               NaN            NaN   
7   8            8         NaN               NaN            NaN   
8   9            9         NaN               NaN            NaN   

                                 application_process  \
0                         Walk in or apply by phone.   
1                 Apply by phone for an appointment.   
2        Phone for information (403-4300 Ext. 4322).   
3                                    Apply by phone.   
4                             Phone for information.   
5  Walk in or apply by phone for membership appli...   
6  Apply by phone or be referred by a doctor, soc...   
7                                    Apply by phone.   
8  Walk in. Proof of residency in California requ...   

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...   
1       Residents of San Mateo County age 55 or over   
2  Older adults age 55 or over who can benefit fr...   
3  Parents, children, families with problems of c...   
4  Low-income working families with children tran...   
5                                            Any age   
6  Older adults who have memory or sensory loss, ...   
7  Senior citizens age 60 or over, disabled indiv...   
8     Ethnic minorities, especially Spanish speaking   

                                         description  \
0  A walk-in center for older adults that provide...   
1  Provides training and job placement to eligibl...   
2  Offers supportive counseling services to San M...   
3  Provides supervised visitation services and a ...   
4  Provides fixed 8% short term loans to eligible...   
5  A multipurpose center offering a wide variety ...   
6  Rosener House is a day center for older adults...   
7  Delivers a hot meal to the home of persons age...   
8  Provides general reading material, including b...   

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...   
1  Age 55 or over, county resident and willing an...   NaN  ...   
2        Resident of San Mateo County age 55 or over   NaN  ...   
3                                               None   NaN  ...   
4  Eligibility: Low-income family with legal cust...   NaN  ...   
5                                               None   NaN  ...   
6                                     Age 18 or over   NaN  ...   
7            Homebound person unable to cook or shop   NaN  ...   
8    Resident of California to obtain a library card   NaN  ...   

                                            keywords languages  \
0  ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
1  EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN   
2  Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN   
3  INDIVIDUAL AND FAMILY DEVELOPMENT SERVICES, Gr...       NaN   
4     COMMUNITY SERVICES, Speakers, Automobile Loans       NaN   
5  ADULT PROTECTION AND CARE SERVICES, In-Home Su...       NaN   
6  ADULT PROTECTION AND CARE SERVICES, Adult Day ...       NaN   
7  ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
8  EDUCATION SERVICES, Library, Libraries, Public...       NaN   

                                   name required_documents  \
0       Fair Oaks Adult Activity Center                NaN   
1      Second Career Employment Program                NaN   
2                Senior Peer Counseling                NaN   
3              Family Visitation Center                NaN   
4     E

In [ ]:
max(df["location_id"])

22

In [ ]:
df.iloc[0:2]

id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN   
1   2            2         NaN               NaN            NaN   

                  application_process  \
0          Walk in or apply by phone.   
1  Apply by phone for an appointment.   

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...   
1       Residents of San Mateo County age 55 or over   

                                         description  \
0  A walk-in center for older adults that provide...   
1  Provides training and job placement to eligibl...   

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...   
1  Age 55 or over, county resident and willing an...   NaN  ...   

                                            keywords languages  \
0  ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
1  EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN   

                               name required_documents     service_areas  \
0   Fair Oaks Adult Activity Center                NaN             Colma   
1  Second Career Employment Program                NaN  San Mateo County   

   status wait_time website taxonomy_ids  new  
0  active  No wait.     NaN          NaN  NaN  
1  active   Varies.     NaN          NaN  NaN  

[2 rows x 23 columns]

In [ ]:
df.loc[0:2]

id  location_id  program_id accepted_payments alternate_name  \
0   1            1         NaN               NaN            NaN   
1   2            2         NaN               NaN            NaN   
2   3            3         NaN               NaN            NaN   

                           application_process  \
0                   Walk in or apply by phone.   
1           Apply by phone for an appointment.   
2  Phone for information (403-4300 Ext. 4322).   

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...   
1       Residents of San Mateo County age 55 or over   
2  Older adults age 55 or over who can benefit fr...   

                                         description  \
0  A walk-in center for older adults that provide...   
1  Provides training and job placement to eligibl...   
2  Offers supportive counseling services to San M...   

                                         eligibility email  ...  \
0  Age 55 or over for most programs, age 60 or ov...   NaN  ...   
1  Age 55 or over, county resident and willing an...   NaN  ...   
2        Resident of San Mateo County age 55 or over   NaN  ...   

                                            keywords languages  \
0  ADULT PROTECTION AND CARE SERVICES, Meal Sites...       NaN   
1  EMPLOYMENT/TRAINING SERVICES, Job Development,...       NaN   
2  Geriatric Counseling, Older Adults, Gay, Lesbi...       NaN   

                               name required_documents     service_areas  \
0   Fair Oaks Adult Activity Center                NaN             Colma   
1  Second Career Employment Program                NaN  San Mateo County   
2            Senior Peer Counseling                NaN  San Mateo County   

   status wait_time website taxonomy_ids  new  
0  active  No wait.     NaN          NaN  NaN  
1  active   Varies.     NaN          NaN  NaN  
2  active   Varies.     NaN          NaN  NaN  

[3 rows x 23 columns]

In [ ]:
df.iloc[0:2 ,[0,1,2]]

id  location_id  program_id
0   1            1         NaN
1   2            2         NaN

In [ ]:
df.loc[0:2 ,['application_process',	'audience',	'description']]

application_process  \
0                   Walk in or apply by phone.   
1           Apply by phone for an appointment.   
2  Phone for information (403-4300 Ext. 4322).   

                                            audience  \
0  Older adults age 55 or over, ethnic minorities...   
1       Residents of San Mateo County age 55 or over   
2  Older adults age 55 or over who can benefit fr...   

                                         description  
0  A walk-in center for older adults that provide...  
1  Provides training and job placement to eligibl...  
2  Offers supportive counseling services to San M...

In [ ]:
df.drop('application_process',axis=1)

id  location_id  program_id         accepted_payments  \
0    1            1         NaN                       NaN   
1    2            2         NaN                       NaN   
2    3            3         NaN                       NaN   
3    4            4         NaN                       NaN   
4    5            5         NaN                       NaN   
5    6            6         NaN                       NaN   
6    7            7         NaN                       NaN   
7    8            8         NaN                       NaN   
8    9            9         NaN                       NaN   
9   10           10         NaN                       NaN   
10  11           11         NaN                       NaN   
11  12           12         NaN                       NaN   
12  13           13         NaN                       NaN   
13  14           14         NaN                       NaN   
14  15           15         NaN                       NaN   
15  16           16         NaN                       NaN   
16  17           17         NaN                       NaN   
17  18           18         NaN                       NaN   
18  19           19         NaN                       NaN   
19  20           20         NaN                       NaN   
20  21           21         NaN                       NaN   
21  22           22         NaN  Cash, Check, Credit Card   
22  23           22         NaN                       NaN   

           alternate_name                                           audience  \
0                     NaN  Older adults age 55 or over, ethnic minorities...   
1                     NaN       Residents of San Mateo County age 55 or over   
2                     NaN  Older adults age 55 or over who can benefit fr...   
3                     NaN  Parents, children, families with problems of c...   
4                     NaN  Low-income working families with children tran...   
5                     NaN                                            Any age   
6                     NaN  Older adults who have memory or sensory loss, ...   
7                     NaN  Senior citizens age 60 or over, disabled indiv...   
8                     NaN     Ethnic minorities, especially Spanish speaking   
9                     NaN                                                NaN   
10                    NaN                                                NaN   
11                    NaN  Adults, parents, children in 1st-12th grades i...   
12                    NaN                                                NaN   
13                    NaN  Individuals or families with low or no income ...   
14                    NaN  Adult alcoholic/drug addictive men and women w...   
15                    NaN                                                NaN   
16                    NaN                                                NaN   
17                    NaN                                                NaN   
18                    NaN                                                NaN   
19                    NaN                                                NaN   
20                    NaN                                                NaN   
21  Fotos para pasaportes  Profit and nonprofit businesses, the public, m...   
22                    NaN  Second service and nonprofit businesses, the p...   

                                          description  \
0   A walk-in center for older adults that provide...   
1   Provides training and job placement to eligibl...   
2   Offers supportive counseling services to San M...   
3   Provides supervised visitation services and a ...   
4   Provides fixed 8% short term loans to eligible...   
5   A multipurpose center offering a wide variety ...   
6   Rosener House is a day center for older adults...   
7   Delivers a hot meal to the home of persons age...   
8   Provides general reading material, including b...   
9   Provides general reading and media materials

In [ ]:
df.drop(3)

id  location_id  program_id         accepted_payments  \
0    1            1         NaN                       NaN   
1    2            2         NaN                       NaN   
2    3            3         NaN                       NaN   
4    5            5         NaN                       NaN   
5    6            6         NaN                       NaN   
6    7            7         NaN                       NaN   
7    8            8         NaN                       NaN   
8    9            9         NaN                       NaN   
9   10           10         NaN                       NaN   
10  11           11         NaN                       NaN   
11  12           12         NaN                       NaN   
12  13           13         NaN                       NaN   
13  14           14         NaN                       NaN   
14  15           15         NaN                       NaN   
15  16           16         NaN                       NaN   
16  17           17         NaN                       NaN   
17  18           18         NaN                       NaN   
18  19           19         NaN                       NaN   
19  20           20         NaN                       NaN   
20  21           21         NaN                       NaN   
21  22           22         NaN  Cash, Check, Credit Card   
22  23           22         NaN                       NaN   

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.   
1                     NaN                 Apply by phone for an appointment.   
2                     NaN        Phone for information (403-4300 Ext. 4322).   
4                     NaN                             Phone for information.   
5                     NaN  Walk in or apply by phone for membership appli...   
6                     NaN  Apply by phone or be referred by a doctor, soc...   
7                     NaN                                    Apply by phone.   
8                     NaN  Walk in. Proof of residency in California requ...   
9                     NaN  Walk in. Proof of California residency to rece...   
10                    NaN  Walk in. Proof of California residency require...   
11                    NaN  Walk in or apply by phone, email or webpage re...   
12                    NaN  Walk in. Proof of California residency require...   
13                    NaN  Call for appointment. Referral from human serv...   
14                    NaN          Walk in or through other agency referral.   
15                    NaN  Walk in. Written application, identification r...   
16                    NaN                              Call for information.   
17                    NaN  Call for screening appointment. Medical visits...   
18                    NaN     Call for screening appointment (650-347-3648).   
19                    NaN                                           Walk in.   
20                    NaN                    By phone during business hours.   
21  Fotos para pasaportes                  Walk in or apply by phone or mail   
22                    NaN                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, ...   
7   Senior citizens age 60 or over, disabled indiv...   
8      Ethnic minorities, especially Spanish speaking   
9                                                 NaN   
10                                                NaN   
11  Adults, parents, children in 1st-12th grades i...   
12                                                NaN   
13  Individuals or

In [ ]:
df.set_index("application_process")

id  location_id  \
application_process                                                   
Walk in or apply by phone.                           1            1   
Apply by phone for an appointment.                   2            2   
Phone for information (403-4300 Ext. 4322).          3            3   
Apply by phone.                                      4            4   
Phone for information.                               5            5   
Walk in or apply by phone for membership applic...   6            6   
Apply by phone or be referred by a doctor, soci...   7            7   
Apply by phone.                                      8            8   
Walk in. Proof of residency in California requi...   9            9   
Walk in. Proof of California residency to recei...  10           10   
Walk in. Proof of California residency required...  11           11   
Walk in or apply by phone, email or webpage reg...  12           12   
Walk in. Proof of California residency required...  13           13   
Call for appointment. Referral from human servi...  14           14   
Walk in or through other agency referral.           15           15   
Walk in. Written application, identification re...  16           16   
Call for information.                               17           17   
Call for screening appointment. Medical visits ...  18           18   
Call for screening appointment (650-347-3648).      19           19   
Walk in.                                            20           20   
By phone during business hours.                     21           21   
Walk in or apply by phone or mail                   22           22   
Walk in or apply by phone or mail                   23           22   

                                                    program_id  \
application_process                                              
Walk in or apply by phone.                                 NaN   
Apply by phone for an appointment.                         NaN   
Phone for information (403-4300 Ext. 4322).                NaN   
Apply by phone.                                            NaN   
Phone for information.                                     NaN   
Walk in or apply by phone for membership applic...         NaN   
Apply by phone or be referred by a doctor, soci...         NaN   
Apply by phone.                                            NaN   
Walk in. Proof of residency in California requi...         NaN   
Walk in. Proof of California residency to recei...         NaN   
Walk in. Proof of California residency required...         NaN   
Walk in or apply by phone, email or webpage reg...         NaN   
Walk in. Proof of California residency required...         NaN   
Call for appointment. Referral from human servi...         NaN   
Walk in or through other agency referral.                  NaN   
Walk in. Written application, identification re...         NaN   
Call for information.                                      NaN   
Call for screening appointment. Medical visits ...         NaN   
Call for screening appointment (650-347-3648).             NaN   
Walk in.                                                   NaN   
By phone during business hours.                            NaN   
Walk in or apply by phone or mail                          NaN   
Walk in or apply by phone or mail                          NaN   

                                                           accepted_payments  \
application_process                                                            
Walk in or apply by phone.                                               NaN   
Apply by phone for an appointment.                                       NaN   
Phone for information (403-4300 Ext. 4322).                              NaN   
Apply by phone.                                                          NaN   
Phone for information.                                                   NaN   
Walk in or apply by phone for membership applic...               

In [ ]:
df.reset_index()

index  id  location_id  program_id         accepted_payments  \
0       0   1            1         NaN                       NaN   
1       1   2            2         NaN                       NaN   
2       2   3            3         NaN                       NaN   
3       3   4            4         NaN                       NaN   
4       4   5            5         NaN                       NaN   
5       5   6            6         NaN                       NaN   
6       6   7            7         NaN                       NaN   
7       7   8            8         NaN                       NaN   
8       8   9            9         NaN                       NaN   
9       9  10           10         NaN                       NaN   
10     10  11           11         NaN                       NaN   
11     11  12           12         NaN                       NaN   
12     12  13           13         NaN                       NaN   
13     13  14           14         NaN                       NaN   
14     14  15           15         NaN                       NaN   
15     15  16           16         NaN                       NaN   
16     16  17           17         NaN                       NaN   
17     17  18           18         NaN                       NaN   
18     18  19           19         NaN                       NaN   
19     19  20           20         NaN                       NaN   
20     20  21           21         NaN                       NaN   
21     21  22           22         NaN  Cash, Check, Credit Card   
22     22  23           22         NaN                       NaN   

           alternate_name                                application_process  \
0                     NaN                         Walk in or apply by phone.   
1                     NaN                 Apply by phone for an appointment.   
2                     NaN        Phone for information (403-4300 Ext. 4322).   
3                     NaN                                    Apply by phone.   
4                     NaN                             Phone for information.   
5                     NaN  Walk in or apply by phone for membership appli...   
6                     NaN  Apply by phone or be referred by a doctor, soc...   
7                     NaN                                    Apply by phone.   
8                     NaN  Walk in. Proof of residency in California requ...   
9                     NaN  Walk in. Proof of California residency to rece...   
10                    NaN  Walk in. Proof of California residency require...   
11                    NaN  Walk in or apply by phone, email or webpage re...   
12                    NaN  Walk in. Proof of California residency require...   
13                    NaN  Call for appointment. Referral from human serv...   
14                    NaN          Walk in or through other agency referral.   
15                    NaN  Walk in. Written application, identification r...   
16                    NaN                              Call for information.   
17                    NaN  Call for screening appointment. Medical visits...   
18                    NaN     Call for screening appointment (650-347-3648).   
19                    NaN                                           Walk in.   
20                    NaN                    By phone during business hours.   
21  Fotos para pasaportes                  Walk in or apply by phone or mail   
22                    NaN                  Walk in or apply by phone or mail   

                                             audience  \
0   Older adults age 55 or over, ethnic minorities...   
1        Residents of San Mateo County age 55 or over   
2   Older adults age 55 or over who can benefit fr...   
3   Parents, children, families with problems of c...   
4   Low-income working families with children tran...   
5                                             Any age   
6   Older adults who have memory or sensory loss, .

In [ ]:
class learning:

  def __init__ (self,name, no,address):

    self.name = name
    self.no = no
    self.address = address

  def ret(self):
      return self.name ,self.no,self.address


ex = learning("rohan",7447,"okokok")

ex.name

'rohan'

In [ ]:
ex.ret()

('rohan', 7447, 'okokok')


*Polymorphism**


In [ ]:
def test(a,b):
  return a+b


test(5,5)
b = test("mani" ,"kantan")
c = test([1,2],[3,4])

In [ ]:
test(5,5)

10

In [ ]:
b

'manikantan'

In [ ]:
c

[1, 2, 3, 4]

In [ ]:
class social:
  def syllabus(self):
    print("Hey Im social")

class math:
  def syllabus (self):
    print("Hey Im math")


def class_parcer(self):
  for i in self:
    i.syllabus()

socialObj= social()
mathObj = math()

listOf = [socialObj,mathObj]

class_parcer(listOf)


Hey Im social
Hey Im math


Encapsulation

In [ ]:
class atm :
  def  __init__ (self,balance):

    self.__balance = balance

  def deposit (self,amount):
    self.__balance = self.__balance+amount

  def withdraw(self,amount):
    if  self.__balance > amount :
      self.__balance =  self.__balance - amount
      return True
    else:
      return False



bank= atm(5000)



In [ ]:
bank.deposit(5000)


In [ ]:
bank.withdraw(20000)

False

In [ ]:
bank.withdraw(5000)

True

Inheritance

In [ ]:
class parent():
  def method1(self):
    print("this is parent")

class child(parent):
  def method2(self):
    print("this is child1")

class child1(child):
  def method3(self):
    print("this is child2")

class child2(child1,child,parent):
  pass

In [ ]:
child1_obj = child1()


In [ ]:
child1_obj.method2()

this is child1


In [ ]:
child1_obj.method1()

this is parent


In [ ]:
child2_obj = child2()

In [ ]:
child2_obj.method1()

this is parent


In [ ]:
class Car():
  def __init__(self,door,light,color):
    self.door = door
    self.light = light
    self.color = color


car_obj = Car(4,2,"blac")


In [ ]:
car_obj.color

'blac'

In [ ]:
class bmw(Car):
  def __init__ (self,enable):
    self.enable=enable
  pass

In [ ]:
bmw_obj=bmw("Yes")

In [ ]:
bmw_obj.color

AttributeError: 'bmw' object has no attribute 'color'

In [ ]:
class bmw1(Car):
  def __init__(self,door,light,color,enable):
    super().__init__(door,light,color)
    self.enable=enable


In [ ]:
bmw1_obj = bmw1(5,2,"Red","Yes")

In [ ]:
bmw1_obj.color

'Red'

Abstraction


In [ ]:
import abc

class pwskills :

    @abc.abstractmethod
    def student_details(self):
        pass

    @abc.abstractmethod
    def student_assignment(self):
        pass


    @abc.abstractmethod
    def student_marks(self):
        pass

In [ ]:
class data_science(pwskills):

    def student_details(self):
        return "it will try to return a details of data science masters "

    def student_assignment(self):
        return "it will return a details of student assignemnt for data science masters "


In [ ]:
ds = data_science()
ds.student_details()

'it will try to return a details of data science masters '

Decorator

In [ ]:
def deco (fun):
  def inner():
    print("this is the start of fn")
    fun()
    print("this is end of fn")
  return inner

In [ ]:
@deco
def test():
  print(4+5)

In [ ]:
test()

this is the start of fn
9
this is end of fn


Class method
just another way of def __init__

In [ ]:
class learning:

  def __init__ (self,name, no,address):

    self.name = name
    self.no = no
    self.address = address

  def ret(self):
      return self.name ,self.no,self.address


ex = learning("rohan",7447,"okokok")

ex.name

'rohan'

In [ ]:
class learning:
    def __init__ (self,name, no,address):

      self.name = name
      self.no = no
      self.address = address
    @classmethod
    def method1(cls,name,no,address):
        return cls(name,no,address)
    def ret(self):
        return self.name ,self.no,self.address


ex = learning.method1("rohan",7447,"okokok")

ex.name

'rohan'

In [ ]:
class classMethod:
  mobile_no = 7337596569                                                     #class variable

  def __init__(self,name,color):                                               # method to pass variables
    self.name = name
    self.color=color


  @classmethod
  def change_mobile(cls,mobile):                                                  #classMethod
      classMethod.mobile_no=mobile

  @classmethod
  def details(cls,name,color):
    return cls (name,color)

  def ret(self):                                                                                  #instance Method
    print(self.name,self.color,classMethod.mobile_no)



In [ ]:
cls_obj = classMethod("mani","dark")

In [ ]:
cls_obj.ret()

mani dark 7337596569


In [ ]:
cls_obj.details("Mani1","fair")

cls_obj.name

'mani'

In [ ]:
cls_obj.change_mobile(8885112307)

In [ ]:
cls_obj.ret()

mani dark 8885112307


Loggers


In [ ]:
import logging

In [ ]:
logging.basicConfig(filename="test1.log",level = logging.DEBUG ,format = '%(asctime)s %(message)s' )

In [ ]:
NOSET
DEBUG
INFO
WARNING
ERROR
CRITICAL

NameError: name 'NOSET' is not defined

In [ ]:
logging.info("this is my info log")

In [ ]:
logging.debug("this is my debug")

In [ ]:
logging.shutdown()